"""Smoke test: every galaxycbm module imports.

Anchors the reproducibility acceptance from P0 — if a rename or a missing
dependency breaks the tree, this test yells loudly.
"""

from __future__ import annotations

import importlib
import pkgutil

import pytest

import galaxycbm

MODULES = [
    "galaxycbm",
    "galaxycbm.data",
    "galaxycbm.data.statmorph_concepts",
    "galaxycbm.data.labels",
    "galaxycbm.data.cutout_cache",
    "galaxycbm.concepts.heads",
    "galaxycbm.concepts.fidelity",
    "galaxycbm.symbolic",
    "galaxycbm.symbolic.features",
    "galaxycbm.symbolic.fit",
    "galaxycbm.symbolic.eval",
    "galaxycbm.uncertainty",
    "galaxycbm.uncertainty.estimator",
    "galaxycbm.uncertainty.conformal",
    "galaxycbm.baselines",
    "galaxycbm.baselines.linear_cbm",
    "galaxycbm.baselines.xgb_concepts",
    "galaxycbm.baselines.cnn",
    "galaxycbm.baselines.compare",
    "galaxycbm.baselines.data",
    "galaxycbm.robustness",
    "galaxycbm.robustness.sources",
    "galaxycbm.robustness.pipeline",
    "galaxycbm.robustness.metrics",
    "galaxycbm.eval",
    "galaxycbm.eval.aggregate",
    "galaxycbm.eval.consistency",
    "galaxycbm.eval.figures",
    "galaxycbm.eval.style",
    "galaxycbm.eval.tables",
    "galaxycbm.concepts",
    "galaxycbm.symbolic",
    "galaxycbm.uncertainty",
    "galaxycbm.robustness",
    "galaxycbm.baselines",
    "galaxycbm.eval",
    "galaxycbm.utils",
    "galaxycbm.utils.config",
    "galaxycbm.utils.io",
    "galaxycbm.utils.runlog",
    "galaxycbm.utils.seed",
]


@pytest.mark.parametrize("modname", MODULES)
def test_module_imports(modname: str) -> None:
    importlib.import_module(modname)


# Modules that intentionally require the `stage1` extra (torch/lightning/zoobot).
# The base env can't import them; the smoke walker skips them by design.
STAGE1_ONLY_MODULES = {
    "galaxycbm.concepts.dataset",
    "galaxycbm.concepts.model",
}

# Auto-generated by Stage-2 (scripts/train_symbolic.py). May or may not exist on
# a fresh clone; either way it's not part of the human-maintained module list.
GENERATED_MODULES = {
    "galaxycbm.symbolic.exported_rules",
}


def test_walk_packages_matches_manifest() -> None:
    """Every submodule under galaxycbm/ is listed in MODULES (except stage1-only)."""
    prefix = "galaxycbm."
    found = {"galaxycbm"} | {
        m.name for m in pkgutil.walk_packages(galaxycbm.__path__, prefix=prefix)
    }
    missing = found - set(MODULES) - STAGE1_ONLY_MODULES - GENERATED_MODULES
    assert not missing, f"New module(s) not covered by the smoke test: {sorted(missing)}"


def test_version_string_is_populated() -> None:
    assert isinstance(galaxycbm.__version__, str) and galaxycbm.__version__
