"""Auto-generated symbolic classifier — do not edit by hand.

Regenerated by scripts/train_symbolic.py.
Consumers pass a pandas DataFrame with the columns listed in FEATURE_COLUMNS
(the sklearn-safe predicted-concept column names) and receive either a
per-class score DataFrame or an array of argmax labels.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import sympy

CLASSES = ['E', 'Irr', 'S0', 'Sa', 'Sb', 'Sc', 'Sd']
FEATURE_COLUMNS = ['smooth_or_featured__smooth', 'smooth_or_featured__featured_or_disk', 'smooth_or_featured__artifact', 'disk_edge_on__no', 'bar__strong', 'bar__weak', 'bar__no', 'has_spiral_arms__no', 'bulge_size__dominant', 'bulge_size__large', 'bulge_size__moderate', 'bulge_size__small', 'bulge_size__none', 'how_rounded__round', 'how_rounded__in_between', 'how_rounded__cigar_shaped', 'edge_on_bulge__boxy', 'edge_on_bulge__rounded', 'edge_on_bulge__none', 'spiral_winding__tight', 'spiral_winding__medium', 'spiral_winding__loose', 'spiral_arm_count__1', 'spiral_arm_count__2', 'spiral_arm_count__3', 'spiral_arm_count__4', 'spiral_arm_count__more_than_4', 'spiral_arm_count__cant_tell', 'merging__none', 'merging__minor_disturbance', 'merging__major_disturbance', 'merging__merger', 'concentration', 'asymmetry', 'smoothness', 'gini', 'm20', 'sersic_n', 'r_eff_pixels']
EXPRESSIONS = {'E': 'smooth_or_featured__smooth * ((1.0040188 - merging__merger) - ((how_rounded__cigar_shaped - (((smooth_or_featured__featured_or_disk + -0.52061987) - smoothness) - smoothness)) * (smooth_or_featured__featured_or_disk * -0.6904113)))', 'Irr': 'abs((0.02885514 - (merging__merger * exp((merging__merger + merging__none) - merging__major_disturbance))) * ((smoothness * (merging__none * exp((square(how_rounded__round) + spiral_arm_count__more_than_4) + bar__strong))) - 0.36367664))', 'S0': '(smooth_or_featured__featured_or_disk * (((has_spiral_arms__no / exp(how_rounded__cigar_shaped)) + ((((how_rounded__cigar_shaped + 0.08217391) * how_rounded__cigar_shaped) * 0.53461885) * smooth_or_featured__featured_or_disk)) * (1.2183967 - merging__merger))) + -0.008181877', 'Sa': '((((((smooth_or_featured__featured_or_disk * exp(merging__minor_disturbance)) * bulge_size__large) * spiral_winding__tight) * disk_edge_on__no) * (exp(merging__minor_disturbance) - has_spiral_arms__no)) * sqrt(bulge_size__large)) / (0.6362593 - bulge_size__none)', 'Sb': '((0.12820928 * sqrt(spiral_winding__tight * disk_edge_on__no)) + 0.012421057) * ((smooth_or_featured__featured_or_disk / (square(square(bulge_size__large) + (merging__merger + square(has_spiral_arms__no))) + 0.13946718)) * disk_edge_on__no)', 'Sc': 'square(((((bulge_size__dominant - spiral_winding__loose) / exp(bulge_size__none)) / exp(bulge_size__none)) - spiral_winding__medium) * (-0.10453457 - (smooth_or_featured__featured_or_disk / exp((has_spiral_arms__no + merging__merger) + 0.17028452)))) * disk_edge_on__no', 'Sd': 'sqrt(bulge_size__none) * (square(smooth_or_featured__featured_or_disk * (disk_edge_on__no * (((merging__merger + -1.1750648) + has_spiral_arms__no) - bulge_size__moderate))) * spiral_winding__loose)'}

_LAMBDAS: dict | None = None


def _compile() -> dict:
    global _LAMBDAS
    if _LAMBDAS is not None:
        return _LAMBDAS
    ns = {name: sympy.Symbol(name) for name in FEATURE_COLUMNS}
    _LAMBDAS = {}
    for cls, expr_str in EXPRESSIONS.items():
        expr = sympy.sympify(expr_str, locals=ns)
        used = sorted(expr.free_symbols, key=lambda s: s.name)
        fn = sympy.lambdify(used, expr, modules=["numpy"])
        _LAMBDAS[cls] = ([str(s.name) for s in used], fn)
    return _LAMBDAS


def score(X: pd.DataFrame) -> pd.DataFrame:
    lambdas = _compile()
    out = {}
    for cls, (used, fn) in lambdas.items():
        if not used:
            out[cls] = np.full(len(X), float(fn()))
        else:
            vals = [X[name].to_numpy(float) for name in used]
            arr = np.asarray(fn(*vals), dtype=float)
            if arr.ndim == 0:
                arr = np.full(len(X), float(arr))
            out[cls] = arr
    return pd.DataFrame(out, index=X.index)


def predict(X: pd.DataFrame) -> np.ndarray:
    s = score(X)
    return s.idxmax(axis=1).to_numpy()
